### ISSUE TITLE
引入后工程报错

### ISSUE THREAD

**Issue by 1013ray** [ccccjiemo/gles#1]
用命令行引入到鸿蒙项目中工程报错
![1732774118936](https://github.com/user-attachments/assets/78afb0b0-cb3e-4fe3-9d72-b0d7ce582525)
然后我添加了这个方法解决了这个报错
![image](https://github.com/user-attachments/assets/39a92c8e-d6ac-43ff-a377-f1960bc98621)
但是再编译又出现了新的错误如下：该怎么处理？谢谢
![image](https://github.com/user-attachments/assets/0bb06d7c-7272-4e3c-82c7-00a29ae5561b)

**Comment by ccccjiemo** [comment]
导入库推荐使用 `import {gles} from '@jemoc/gles'`，图3错误应该是代码携程`import {gles} from '@jemoc/gles/index'`，编译器找不到库文件，把`import {gles} from '@jemoc/gles/index'`中的index改成大写Index。或者使用推荐写法

**Comment by ccccjiemo** [comment]
使用README中导入库的说明方法，如果还是出现问题，可以先尝试clean project再编译。如果还不能解决，可以把工程拷贝一份，删除重要代码发送给我看看





CC
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ccccjiemo/gles"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月28日(星期四) 下午2:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ccccjiemo/gles] 引入后工程报错 (Issue #1)





 
用命令行引入到鸿蒙项目中工程报错
 1732774118936.jpg (view on web)
 然后我添加了这个方法解决了这个报错
 image.png (view on web)
 但是再编译又出现了新的错误如下：该怎么处理？谢谢
 image.png (view on web)

**Comment by ccccjiemo** [comment]
> 用命令行引入到鸿蒙项目中工程报错 ![1732774118936](https://private-user-images.githubusercontent.com/94347624/390660404-78afb0b0-cb3e-4fe3-9d72-b0d7ce582525.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODEzMzEsIm5iZiI6MTczMjc4MTAzMSwicGF0aCI6Ii85NDM0NzYyNC8zOTA2NjA0MDQtNzhhZmIwYjAtY2IzZS00ZmUzLTlkNzItYjBkN2NlNTgyNTI1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA4MDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZjVkODNhYjZmMTYyYWFkMzRjMjcxZTQ3NjNlYzVmOTY0NWNiNmRhYjI0NGJkNDVlYmQ0Nzg4NjY4MzFkZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2r0i9ziqziN0M28SHo6_DV9rWoOSQHXC_hb_HIay_oI) 然后我添加了这个方法解决了这个报错 ![image](https://private-user-images.githubusercontent.com/94347624/390660648-39a92c8e-d6ac-43ff-a377-f1960bc98621.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODEzMzEsIm5iZiI6MTczMjc4MTAzMSwicGF0aCI6Ii85NDM0NzYyNC8zOTA2NjA2NDgtMzlhOTJjOGUtZDZhYy00M2ZmLWEzNzctZjE5NjBiYzk4NjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA4MDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYmIzZTYxYzNlMDNiMzJlNGFhMzk5NzcwOGJhZTcwYWQ0OGNhN2FmOWM0MmM4ZTYzMjAyOTY5MDEyZjM1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YbUWwK6I9ewyEvqzfqFxXcGU7kiInCeH1xggdqnVUvQ) 但是再编译又出现了新的错误如下：该怎么处理？谢谢 ![image](https://private-user-images.githubusercontent.com/94347624/390660853-0bb06d7c-7272-4e3c-82c7-00a29ae5561b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODEzMzEsIm5iZiI6MTczMjc4MTAzMSwicGF0aCI6Ii85NDM0NzYyNC8zOTA2NjA4NTMtMGJiMDZkN2MtNzI3Mi00ZTNjLTgyYzctMDBhMjlhZTU1NjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA4MDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MDUyYTAxMzZlZDVhODIyMjRhNzMzNzJjZmZiZTg1YWYxZTkzYjRkMDAzYzQyZTBmOWQwZmMxMmQ4ZTlmNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZtKGPdGRNt0eIC6jYHSVWhGWypq8NrgfGjYk0oDBsOk)

导入库推荐使用 import {gles} from '@jemoc/gles'，图3错误应该是代码写成import {gles} from '@jemoc/gles/index'，编译器找不到库文件，把import {gles} from '@jemoc/gles/index'中的index改成大写Index。或者使用推荐写法。目前gles库还属于beta版本，感谢你的反馈

**Comment by 1013ray** [comment]
好的谢谢  我可以用这个方法用openGL画到视频帧里面去吗？类似于加水印得功能

**Comment by ccccjiemo** [comment]
> 好的谢谢 我可以用这个方法用openGL画到视频帧里面去吗？类似于加水印得功能

可以的，在论坛有现成的例子，可以参考https://developer.huawei.com/consumer/cn/forum/topic/0210155920768504185?fid=0109140870620153026。不过是全native实现的。

如果要换成全arkts，可以使用ImageReceiver来接收AvPlayer的画面帧，再使用opengl来渲染到XComponents上。
不过arkts多少都会有性能损失，可能会带来比如画面延迟，帧率降低等问题，这些需要自己评估能否接收。不过一般视频都是30帧率应该都是可以接收的。

ImageReceiver参考https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V13/js-apis-image-V13#imagereceiver9

我今天刚发布了@jemoc/glview组件也可以尝试使用。

**Comment by 1013ray** [comment]
感谢感谢
